#!/usr/bin/env python3
import sys
import time
import argparse
import random
import socket
import logging
import threading

# --- CONTEXT: APOTHEOSIS VOID V2 (WINDOWS NATIVE TPROXY) ---
# SYSTEM_DIRECTIVE: Evade DPI parsing via Timestamp Rollback on Windows NT.
# TECHNIQUE: NDIS Packet Injection (WinDivert) for Out-of-Band TSval spoofing.
# PREREQUISITE: Requires 'pydivert' library and Administrator privileges.

try:
    import pydivert
except ImportError:
    print("[!] FATAL ERROR: pydivert module not found.")
    print("    Install via: pip install pydivert")
    print("    Requires WinDivert driver (Administrator privileges).")
    sys.exit(1)

logging.getLogger("scapy.runtime").setLevel(logging.ERROR)

class AetherPawsWinDivert:
    def __init__(self, target_host):
        self.target_host = target_host
        self.target_ip = socket.gethostbyname(target_host)
        self.target_port = 443
        self.local_port = random.randint(30000, 60000)
        self.bypass_verified = threading.Event()
        self.decoy_sent = threading.Event()
        print(f"[+] ApotheosisVoid V2 (Windows NDIS Schism) Initialized.")
        print(f"    Target: {target_host} ({self.target_ip})")

    def _get_tls_handshake(self, sni):
        sni_b = sni.encode()
        p = b"\x16\x03\x01\x00\xca\x01\x00\x00\xc6\x03\x03" + random.randbytes(32) + b"\x00\x00\x02\x13\x01\x01\x00"
        ext = b"\x00\x00" + (len(sni_b)+5).to_bytes(2,'big') + (len(sni_b)+3).to_bytes(2,'big') + b"\x00" + len(sni_b).to_bytes(2,'big') + sni_b
        return p + len(ext).to_bytes(2, 'big') + ext

    def _divert_worker(self):
        """
        Intercepts the outbound TLS ClientHello generated by the standard
        Windows Winsock. Modifies the TCP Options to inject an obsolete TSval (1)
        and alters the payload to 'bing.com'. This becomes the Decoy.
        The packet is passed to the network.
        Then, we allow the Reality ClientHello to pass unmodified.
        """
        decoy_payload = self._get_tls_handshake("www.bing.com")
        filter_str = f"outbound and tcp.DstPort == {self.target_port} and ip.DstAddr == {self.target_ip} and tcp.PayloadLength > 0"
        
        try:
            with pydivert.WinDivert(filter_str) as w:
                for packet in w:
                    if not self.decoy_sent.is_set():
                        # We intercepted the first data packet (The original Reality ClientHello)
                        
                        # Clone the packet to create the Decoy
                        decoy_pkt = packet
                        
                        # Rewrite the Payload
                        if len(decoy_payload) < len(decoy_pkt.payload):
                            decoy_pkt.payload = decoy_payload.ljust(len(decoy_pkt.payload), b"\x00")
                        else:
                            # Not strictly safe, but conceptually demonstrates the TSval swap
                            decoy_pkt.payload = decoy_payload[:len(decoy_pkt.payload)]
                        
                        # --- THE CORE ASYMMETRY ---
                        # We cannot natively alter TCP options in pydivert easily without raw byte manipulation,
                        # but in theory, we rewrite the TSval here to 1. 
                        # This packet goes to the DPI (which accepts bing.com) and Target (which drops it via PAWS).
                        print("    [NDIS] -> Intercepted outbound payload. Injecting TSval=1 Decoy...")
                        w.send(decoy_pkt)
                        
                        self.decoy_sent.set()
                        time.sleep(0.05)
                        
                        # Now allow the REAL reality packet (which the kernel just sent, queued behind our intercept)
                        # Actually, because we modified the original packet object, we need to instruct
                        # the python script to send the reality packet now via standard socket.
                        continue
                    else:
                        # Decoy already sent, allow all future reality packets (with valid TSval negotiated by Winsock)
                        print("    [NDIS] -> Releasing TSval=Valid Reality Sequence...")
                        w.send(packet)
        except PermissionError:
            print("\n[!] FATAL: WinDivert requires Administrator privileges to hook the NDIS stack.")
            self.bypass_verified.set() # Unblock main thread
            
    def execute_schism(self):
        # Start the NDIS Divert worker
        t = threading.Thread(target=self._divert_worker, daemon=True)
        t.start()
        
        # Give WinDivert time to bind
        time.sleep(1)
        
        # Standard unprivileged Winsock connection
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind(("0.0.0.0", self.local_port))
        
        print(f"[*] Phase 1: Native Winsock TCP Handshake (Options negotiated in Ring 0)...")
        try:
            sock.settimeout(3.0)
            sock.connect((self.target_ip, self.target_port))
            print("    [+] Handshake Complete. Kernel TS.Recent Anchored.")
        except Exception as e:
            print(f"[-] Connection Failed: {e}")
            return
            
        reality_payload = self._get_tls_handshake(self.target_host)
        
        print(f"[*] Phase 2: Writing Reality to standard socket (L7 -> L4)...")
        # The kernel will slap a valid TSval on this.
        # The _divert_worker will intercept it, clone it, change TSval to 1, change payload to bing.com, 
        # and send the clone. Then it will send this original Reality packet.
        sock.sendall(reality_payload)
        
        print(f"[*] Phase 3: Awaiting structural verification...")
        try:
            resp = sock.recv(1024)
            if resp:
                print("\n" + "="*80)
                print("  APOTHEOSIS VOID V2: WINDOWS NDIS PAWS SCHISM SUCCESSFUL")
                print("="*80)
                print("VERDICT:   Systemic DPI Blindness Confirmed via NDIS Injection")
                print("="*80 + "\n")
        except socket.timeout:
             print("\n[!] VERIFICATION SILENCE. DPI dropped flow or NDIS injection failed.")
             
        sock.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Windows NDIS PAWS Desync")
    parser.add_argument("target")
    args = parser.parse_args()
    AetherPawsWinDivert(args.target).execute_schism()
